version: '3'
services:
  web:
    image: andela-devops-assessment
    build: ./web-server
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./web-server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"

    ports:
      - "27017:27017"
  adminmongo:
    image: "mrvautin/adminmongo"

    ports:
      - "1234:1234"